-- 관리자 사용자 통계의 기간 조건과 그룹 집계를 지원하는 운영 인덱스를 추가한다.
-- 이 스크립트는 기존 운영 스키마에 한 번만 적용한다.

ALTER TABLE `TM_USERXM`
    ADD INDEX `IX_TM_USERXM_JOIN` (`JOIN_DATE`, `USER_NUMB`),
    ADD INDEX `IX_TM_USERXM_PROF_FEED` (`USER_STAT`, `PROF_DATE` DESC, `USER_NUMB`),
    ADD INDEX `IX_TM_USERXM_BGIM_FEED` (`USER_STAT`, `BGIM_DATE` DESC, `USER_NUMB`);

ALTER TABLE `TB_LOGHIS`
    ADD INDEX `IX_TB_LOGHIS_DATE` (`LOGN_DATE`, `USER_NUMB`);

ALTER TABLE `TM_REPORT`
    ADD INDEX `IX_TM_REPORT_REGI` (`REGI_DATE`, `USER_NUMB`),
    ADD INDEX `IX_TM_REPORT_FEED` (`USER_NUMB`, `PUBC_YSNO`, `PUBC_DATE` DESC, `REPT_NUMB` DESC);

ALTER TABLE `TB_REPLXX`
    ADD INDEX `IX_TB_REPLXX_REGI` (`REGI_DATE`, `USER_NUMB`),
    ADD INDEX `IX_TB_REPLXX_TAGT` (`TAGT_TYPE`, `TAGT_NUMB`, `UPER_NUMB`, `REGI_DATE` DESC);

ALTER TABLE `TB_LIKEXX`
    ADD INDEX `IX_TB_LIKEXX_REGI` (`REGI_DATE`, `USER_NUMB`);

ALTER TABLE `TB_FOLLOW`
    ADD INDEX `IX_TB_FOLLOW_REGI` (`REGI_DATE`, `USER_NUMB`);

ALTER TABLE `TB_RDATDX`
    ADD INDEX `IX_TB_RDATDX_DATE` (`READ_DATE`, `USER_NUMB`);

ALTER TABLE `TM_RDTMRX`
    ADD INDEX `IX_TM_RDTMRX_ACTIVE` (`USER_NUMB`, `TMRX_STAT`, `STRT_DATE`),
    ADD INDEX `IX_TM_RDTMRX_ALRM` (`TMRX_STAT`, `SEND_DATE`, `ALRM_DATE`, `TMRX_NUMB`),
    ADD INDEX `IX_TM_RDTMRX_ENDX` (`ENDX_DATE`, `USER_NUMB`),
    ADD INDEX `IX_TM_RDTMRX_REPT` (`REPT_NUMB`);

ALTER TABLE `TH_USWTHD`
    ADD INDEX `IX_TH_USWTHD_REQU` (`REQU_DATE`, `WTHD_TYPE`),
    ADD INDEX `IX_TH_USWTHD_RCOV` (`RCOV_DATE`, `USER_NUMB`);

ALTER TABLE `TH_USSPND`
    ADD INDEX `IX_TH_USSPND_STRT` (`STRT_DATE`, `USER_NUMB`);

-- 탈퇴한 OAuth 계정의 과거 회원 번호와 유효 제재 연결 조회를 지원한다.
ALTER TABLE `TH_USWTHD`
    ADD INDEX `IX_TH_USWTHD_IDHS` (`USER_IDHS`, `USER_NUMB`);

-- 동일 사용자의 동일 대상 버전 재신고와 동시 요청 중복 접수를 차단한다.
-- 동일 번호의 콘텐츠가 수정되면 새로운 버전으로 집계하도록 대상 해시를 포함한다.
ALTER TABLE `TH_CMPLNT`
    DROP INDEX `UK_TH_CMPLNT_USER_TAGT`,
    DROP INDEX `IX_TH_CMPLNT_TAGT`,
    ADD UNIQUE INDEX `UK_TH_CMPLNT_USER_TAGT` (`USER_NUMB`, `TAGT_TYPE`, `TAGT_NUMB`, `TAGT_HASH`),
    ADD INDEX `IX_TH_CMPLNT_TAGT` (`TAGT_TYPE`, `TAGT_NUMB`, `TAGT_HASH`, `CMPL_STAT`, `REGI_DATE`);

-- 현재 사용자 상세의 받은 신고 이력을 최신순으로 조회한다.
ALTER TABLE `TH_CMPLNT`
    ADD INDEX `IX_TH_CMPLNT_TAGT_USER` (`TAGT_USER`, `REGI_DATE`, `CMPL_NUMB`);

-- 동일 대상 버전의 자동 조치 이력이 한 번만 생성되도록 보장한다.
ALTER TABLE `TH_CMACTN`
    DROP INDEX `UK_TH_CMACTN_TAGT_ORDR`,
    ADD UNIQUE INDEX `UK_TH_CMACTN_TAGT_ORDR` (`TAGT_TYPE`, `TAGT_NUMB`, `TAGT_HASH`, `ACTN_ORDR`);

-- 관리자 전용 프로필 이미지 증거의 동일 버전 중복 저장과 사용자별 만료 조회를 지원한다.
ALTER TABLE `TH_CMEVDC`
    ADD UNIQUE INDEX `UK_TH_CMEVDC_TAGT_HASH` (`TAGT_TYPE`, `TAGT_NUMB`, `TAGT_HASH`),
    ADD INDEX `IX_TH_CMEVDC_TAGT_USER` (`TAGT_USER`, `REGI_DATE`, `EVDC_NUMB`);
