-- 관리자 사용자 통계의 기간 조건과 그룹 집계를 지원하는 운영 인덱스를 추가한다.
-- 이 스크립트는 기존 운영 스키마에 한 번만 적용한다.

ALTER TABLE `TM_USERXM`
    ADD INDEX `IX_TM_USERXM_JOIN` (`JOIN_DATE`, `USER_NUMB`);

ALTER TABLE `TB_LOGHIS`
    ADD INDEX `IX_TB_LOGHIS_DATE` (`LOGN_DATE`, `USER_NUMB`);

ALTER TABLE `TM_REPORT`
    ADD INDEX `IX_TM_REPORT_REGI` (`REGI_DATE`, `USER_NUMB`);

ALTER TABLE `TB_REPLXX`
    ADD INDEX `IX_TB_REPLXX_REGI` (`REGI_DATE`, `USER_NUMB`);

ALTER TABLE `TB_LIKEXX`
    ADD INDEX `IX_TB_LIKEXX_REGI` (`REGI_DATE`, `USER_NUMB`);

ALTER TABLE `TB_FOLLOW`
    ADD INDEX `IX_TB_FOLLOW_REGI` (`REGI_DATE`, `USER_NUMB`);

ALTER TABLE `TB_RDATDX`
    ADD INDEX `IX_TB_RDATDX_DATE` (`READ_DATE`, `USER_NUMB`);

ALTER TABLE `TM_RDTMRX`
    ADD INDEX `IX_TM_RDTMRX_ACTIVE` (`USER_NUMB`, `TMRX_STAT`, `STRT_DATE`),
    ADD INDEX `IX_TM_RDTMRX_ALRM` (`TMRX_STAT`, `SEND_DATE`, `ALRM_DATE`, `TMRX_NUMB`),
    ADD INDEX `IX_TM_RDTMRX_ENDX` (`ENDX_DATE`, `USER_NUMB`),
    ADD INDEX `IX_TM_RDTMRX_REPT` (`REPT_NUMB`);

ALTER TABLE `TH_USWTHD`
    ADD INDEX `IX_TH_USWTHD_REQU` (`REQU_DATE`, `WTHD_TYPE`),
    ADD INDEX `IX_TH_USWTHD_RCOV` (`RCOV_DATE`, `USER_NUMB`);

ALTER TABLE `TH_USSPND`
    ADD INDEX `IX_TH_USSPND_STRT` (`STRT_DATE`, `USER_NUMB`);

-- 탈퇴한 OAuth 계정의 과거 회원 번호와 유효 제재 연결 조회를 지원한다.
ALTER TABLE `TH_USWTHD`
    ADD INDEX `IX_TH_USWTHD_IDHS` (`USER_IDHS`, `USER_NUMB`);
