-- 삭제 상태 알림의 보존기간 기준일과 정리 조회 인덱스 추가
ALTER TABLE `TB_ALIMXX`
  ADD COLUMN `UPDT_DATE` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '수정 일시' AFTER `DELT_YSNO`,
  ADD KEY `IX_TB_ALIMXX_CLEANUP` (`DELT_YSNO`, `UPDT_DATE`);
