-- 삭제된 회원 관심분야 테이블을 단일 관심분야 코드 구조로 다시 생성한다
CREATE TABLE TB_USINTR (
  USER_NUMB bigint NOT NULL COMMENT '사용자 번호',
  INTR_CODE varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT 'CATE_CODE 하위 관심분야 세부코드',
  REGI_DATE datetime(6) NOT NULL COMMENT '등록 일시',
  PRIMARY KEY (USER_NUMB, INTR_CODE),
  KEY IX_TB_USINTR_RECM (INTR_CODE, USER_NUMB),
  CONSTRAINT FK_TB_USINTR_01 FOREIGN KEY (USER_NUMB) REFERENCES TM_USERXM (USER_NUMB) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='회원 독서 관심분야';
