-- Sadari 애플리케이션이 사용하는 MySQL 저장 함수와 프로시저를 생성한다
-- 바이너리 로그가 활성화된 서버는 관리자 계정으로 log_bin_trust_function_creators를 1로 설정한 뒤 실행한다
SET NAMES utf8mb4;

DELIMITER $$

DROP FUNCTION IF EXISTS FN_GET_CODE_NAME$$
CREATE FUNCTION FN_GET_CODE_NAME(
    P_COMM_CODE VARCHAR(255),
    P_COMD_CODE VARCHAR(255),
    P_OPT_CODE VARCHAR(255)
) RETURNS VARCHAR(1000)
READS SQL DATA
SQL SECURITY INVOKER
BEGIN
    DECLARE V_CODE_NAME VARCHAR(1000) DEFAULT P_COMD_CODE;
    DECLARE CONTINUE HANDLER FOR NOT FOUND SET V_CODE_NAME = P_COMD_CODE;

    SELECT CASE P_OPT_CODE
               WHEN 'OPT1' THEN COALESCE(OPT1_NAME, COMD_NAME)
               WHEN 'OPT2' THEN COALESCE(OPT2_NAME, COMD_NAME)
               WHEN 'OPT3' THEN COALESCE(OPT3_NAME, COMD_NAME)
               WHEN 'OPT4' THEN COALESCE(OPT4_NAME, COMD_NAME)
               ELSE COMD_NAME
           END
      INTO V_CODE_NAME
      FROM TB_CODEXD
     WHERE COMM_CODE = P_COMM_CODE
       AND COMD_CODE = P_COMD_CODE
       AND COALESCE(USEE_YSNO, 'Y') = 'Y'
     LIMIT 1;

    RETURN COALESCE(V_CODE_NAME, P_COMD_CODE);
END$$

DROP FUNCTION IF EXISTS FN_GET_LOCAL_DATE_STR$$
CREATE FUNCTION FN_GET_LOCAL_DATE_STR(
    P_DATE_STR VARCHAR(255),
    P_LOCALE VARCHAR(50)
) RETURNS VARCHAR(255)
DETERMINISTIC
NO SQL
SQL SECURITY INVOKER
BEGIN
    IF P_DATE_STR IS NULL THEN
        RETURN NULL;
    END IF;

    IF LOWER(COALESCE(P_LOCALE, 'ko')) LIKE 'ko%'
            AND P_DATE_STR REGEXP '^[0-9]{8}$' THEN
        RETURN CONCAT(
            SUBSTR(P_DATE_STR, 1, 4), '.',
            SUBSTR(P_DATE_STR, 5, 2), '.',
            SUBSTR(P_DATE_STR, 7, 2)
        );
    END IF;

    RETURN P_DATE_STR;
END$$

DROP FUNCTION IF EXISTS FN_GET_FOLW_STAT$$
CREATE FUNCTION FN_GET_FOLW_STAT(
    P_USER_NUMB BIGINT,
    P_FLOW_NUMB BIGINT
) RETURNS VARCHAR(1000)
READS SQL DATA
SQL SECURITY INVOKER
BEGIN
    IF EXISTS (
        SELECT 1
          FROM TB_FOLLOW
         WHERE USER_NUMB = P_USER_NUMB
           AND FLOW_NUMB = P_FLOW_NUMB
    ) THEN
        RETURN FN_GET_CODE_NAME('FOLW_STAT', 'FOLLOWING', NULL);
    END IF;

    IF EXISTS (
        SELECT 1
          FROM TB_FOLLOW
         WHERE USER_NUMB = P_FLOW_NUMB
           AND FLOW_NUMB = P_USER_NUMB
    ) THEN
        RETURN FN_GET_CODE_NAME('FOLW_STAT', 'BOTH_FOLLOW', NULL);
    END IF;

    RETURN FN_GET_CODE_NAME('FOLW_STAT', 'FOLLOW', NULL);
END$$

DROP FUNCTION IF EXISTS FN_GET_ADMIN_NAME$$
CREATE FUNCTION FN_GET_ADMIN_NAME(
    P_ADMN_NUMB VARCHAR(255)
) RETURNS VARCHAR(255)
READS SQL DATA
SQL SECURITY INVOKER
BEGIN
    DECLARE V_ADMN_NAME VARCHAR(255) DEFAULT P_ADMN_NUMB;
    DECLARE CONTINUE HANDLER FOR NOT FOUND SET V_ADMN_NAME = P_ADMN_NUMB;

    SELECT ADMN_NAME
      INTO V_ADMN_NAME
      FROM TM_ADMINX
     WHERE CAST(ADMN_NUMB AS CHAR) = P_ADMN_NUMB
     LIMIT 1;

    RETURN COALESCE(V_ADMN_NAME, P_ADMN_NUMB);
END$$

DROP PROCEDURE IF EXISTS PR_DEL_HARD_DELETE_USER$$
CREATE PROCEDURE PR_DEL_HARD_DELETE_USER(
    IN P_USER_NUMB BIGINT
)
MODIFIES SQL DATA
SQL SECURITY INVOKER
BEGIN
    UPDATE TB_LOGHIS
       SET USER_NUMB = NULL
     WHERE USER_NUMB = P_USER_NUMB;

    DELETE CHILD
      FROM TB_REPLXX CHILD
      JOIN TB_REPLXX PARENT
        ON PARENT.REPT_NUMB = CHILD.REPT_NUMB
       AND PARENT.REPL_NUMB = CHILD.UPER_NUMB
     WHERE PARENT.USER_NUMB = P_USER_NUMB;

    DELETE REPLY
      FROM TB_REPLXX REPLY
      JOIN TM_REPORT REPORT
        ON REPORT.REPT_NUMB = REPLY.REPT_NUMB
     WHERE REPORT.USER_NUMB = P_USER_NUMB;

    DELETE FROM TB_REPLXX
     WHERE USER_NUMB = P_USER_NUMB;

    DELETE LIKEX
      FROM TB_LIKEXX LIKEX
 LEFT JOIN TM_REPORT REPORT
        ON LIKEX.TAGT_TYPE = 'REPORT'
       AND LIKEX.TAGT_NUMB = REPORT.REPT_NUMB
     WHERE LIKEX.USER_NUMB = P_USER_NUMB
        OR REPORT.USER_NUMB = P_USER_NUMB;

    DELETE FROM TB_FOLLOW
     WHERE USER_NUMB = P_USER_NUMB
        OR FLOW_NUMB = P_USER_NUMB;

    DELETE FROM TB_ALIMXX
     WHERE USER_NUMB = P_USER_NUMB;

    DELETE FROM TB_PSHSUB
     WHERE USER_NUMB = P_USER_NUMB;

    DELETE FROM TM_GOALXM
     WHERE USER_NUMB = P_USER_NUMB;

    DELETE FROM TM_REPORT
     WHERE USER_NUMB = P_USER_NUMB;

    UPDATE TM_USERXM
       SET PROF_NUMB = NULL
         , BGIM_NUMB = NULL
     WHERE USER_NUMB = P_USER_NUMB;

    DELETE FROM TM_FILEXM
     WHERE REGI_USER = P_USER_NUMB;

    DELETE FROM TM_USERXM
     WHERE USER_NUMB = P_USER_NUMB;
END$$

DELIMITER ;
