spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: sadari
    password: tkekfl12
    driver-class-name: oracle.jdbc.OracleDriver
  application:
    name: sadari
  config:
    activate:
      on-profile: loc

mybatis:
  mapper-locations: classpath:org/our/sadari/**/*.xml
  type-aliases-package: org.our.sadari.**.vo
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
